#!/usr/bin/env bash
set -e
# Diagnostico + arreglo puntual para el pedido DEMO-1788524290382 (o
# cualquier otro) que no se puede consultar en /seguimiento con NINGUN
# codigo postal.
#
# El backfill anterior (apply_fix_codigo_postal_demo.sh) solo corrige los 4
# clientes de demo concretos del seed (500010-500013) -- si Raul ha probado
# varios codigos postales y ninguno funciona para DEMO-1788524290382, lo mas
# probable es que ese pedido concreto sea de OTRO cliente distinto a esos 4
# (por ejemplo uno creado a mano en algun momento anterior a que se
# exigiera codigo postal en todas las vias de alta), y ese backfill no lo
# cubre.
#
# Este script nuevo, backend/prisma/fix-order-postal-code.ts (comando
# "npm run db:fix-order-cp"), va directo al pedido por su numero -- no hace
# falta saber de antemano que cliente es ni tocar la base de datos a mano:
#
#   Solo diagnostica (no cambia nada):
#     cd backend && npm run db:fix-order-cp -- DEMO-1788524290382
#
#   Diagnostica Y rellena el codigo postal que falte (con el que le pases):
#     cd backend && npm run db:fix-order-cp -- DEMO-1788524290382 28906
#
# Imprime el cliente, direccion, poblacion, provincia y el codigo postal
# actual del punto de entrega de ese pedido -- si ya tiene codigo postal,
# lo dice explicitamente (con lo cual el problema seria otro, no el codigo
# postal, y habria que revisarlo aparte). No sobrescribe un codigo postal
# que ya exista, solo rellena si esta vacio.
#
# Sin cambios de schema. Ejecutar desde la raiz del repo. Este script NO
# ejecuta el diagnostico por ti al final (necesita que le pases el numero de
# pedido exacto) -- hazlo tu mismo con el comando de arriba despues de que
# termine de escribir los ficheros.

echo "Escribiendo backend/package.json..."
mkdir -p "$(dirname backend/package.json)"
base64 -d > backend/package.json <<'B64EOF'
ewogICJuYW1lIjogInRtcy1iYWNrZW5kIiwKICAidmVyc2lvbiI6ICIwLjEuMCIsCiAgInByaXZh
dGUiOiB0cnVlLAogICJ0eXBlIjogImNvbW1vbmpzIiwKICAic2NyaXB0cyI6IHsKICAgICJkZXYi
OiAidHN4IHdhdGNoIHNyYy9pbmRleC50cyIsCiAgICAiYnVpbGQiOiAidHNjIC1wIHRzY29uZmln
Lmpzb24gJiYgdHNjLWFsaWFzIC1wIHRzY29uZmlnLmpzb24iLAogICAgInN0YXJ0IjogIm5vZGUg
ZGlzdC9pbmRleC5qcyIsCiAgICAicHJpc21hOmdlbmVyYXRlIjogInByaXNtYSBnZW5lcmF0ZSIs
CiAgICAicHJpc21hOm1pZ3JhdGUiOiAicHJpc21hIG1pZ3JhdGUgZGV2IiwKICAgICJkYjpzZWVk
IjogInRzeCBwcmlzbWEvc2VlZC50cyIsCiAgICAiZGI6c2VlZDpzYWZlIjogInRzeCBwcmlzbWEv
c2VlZC50cyB8fCB0cnVlIiwKICAgICJkZW1vOnJlZnJlc2gtdG9kYXkiOiAidHN4IHByaXNtYS9y
ZWZyZXNoLWRlbW8tcm91dGUudHMiLAogICAgImRiOnNlZWQ6c2VnbWVudGF0aW9uIjogInRzeCBw
cmlzbWEvc2VlZC1zZWdtZW50YXRpb24tcnVsZXMudHMiLAogICAgImRiOmltcG9ydC1zdXJ0aWRv
IjogInRzeCBwcmlzbWEvaW1wb3J0LXN1cnRpZG8udHMiLAogICAgImRiOmJhY2tmaWxsLWRlbW8t
Y3AiOiAidHN4IHByaXNtYS9iYWNrZmlsbC1kZW1vLXBvc3RhbC1jb2Rlcy50cyIsCiAgICAiZGI6
Zml4LW9yZGVyLWNwIjogInRzeCBwcmlzbWEvZml4LW9yZGVyLXBvc3RhbC1jb2RlLnRzIiwKICAg
ICJ0ZXN0IjogInZpdGVzdCBydW4iLAogICAgInRlc3Q6aW50ZWdyYXRpb24iOiAidml0ZXN0IHJ1
biAtLWNvbmZpZyB2aXRlc3QuaW50ZWdyYXRpb24uY29uZmlnLnRzIiwKICAgICJ0ZXN0OmFsbCI6
ICJucG0gcnVuIHRlc3QgJiYgbnBtIHJ1biB0ZXN0OmludGVncmF0aW9uIgogIH0sCiAgImRlcGVu
ZGVuY2llcyI6IHsKICAgICJAcHJpc21hL2NsaWVudCI6ICJeNS4yMC4wIiwKICAgICJiY3J5cHRq
cyI6ICJeMi40LjMiLAogICAgImNvcnMiOiAiXjIuOC41IiwKICAgICJkYXlqcyI6ICJeMS4xMS4x
MyIsCiAgICAiZG90ZW52IjogIl4xNi40LjUiLAogICAgImV4cHJlc3MiOiAiXjQuMjEuMCIsCiAg
ICAiZXhwcmVzcy1hc3luYy1lcnJvcnMiOiAiXjMuMS4xIiwKICAgICJleHByZXNzLXJhdGUtbGlt
aXQiOiAiXjcuNC4xIiwKICAgICJoZWxtZXQiOiAiXjcuMS4wIiwKICAgICJqc29ud2VidG9rZW4i
OiAiXjkuMC4yIiwKICAgICJtb3JnYW4iOiAiXjEuMTAuMCIsCiAgICAidXVpZCI6ICJeOS4wLjEi
LAogICAgInhsc3giOiAiXjAuMTguNSIsCiAgICAiem9kIjogIl4zLjIzLjgiCiAgfSwKICAiZGV2
RGVwZW5kZW5jaWVzIjogewogICAgIkB0eXBlcy9iY3J5cHRqcyI6ICJeMi40LjYiLAogICAgIkB0
eXBlcy9jb3JzIjogIl4yLjguMTciLAogICAgIkB0eXBlcy9leHByZXNzIjogIl40LjE3LjIxIiwK
ICAgICJAdHlwZXMvanNvbndlYnRva2VuIjogIl45LjAuNyIsCiAgICAiQHR5cGVzL21vcmdhbiI6
ICJeMS45LjkiLAogICAgIkB0eXBlcy9ub2RlIjogIl4yMC4xNi41IiwKICAgICJAdHlwZXMvc3Vw
ZXJ0ZXN0IjogIl42LjAuMiIsCiAgICAiQHR5cGVzL3V1aWQiOiAiXjkuMC44IiwKICAgICJwcmlz
bWEiOiAiXjUuMjAuMCIsCiAgICAic3VwZXJ0ZXN0IjogIl43LjAuMCIsCiAgICAidHNjLWFsaWFz
IjogIl4xLjguMTAiLAogICAgInRzeCI6ICJeNC4xOS4xIiwKICAgICJ0eXBlc2NyaXB0IjogIl41
LjYuMiIsCiAgICAidml0ZXN0IjogIl4yLjEuMSIKICB9Cn0K
B64EOF

echo "Escribiendo backend/prisma/fix-order-postal-code.ts..."
mkdir -p "$(dirname backend/prisma/fix-order-postal-code.ts)"
base64 -d > backend/prisma/fix-order-postal-code.ts <<'B64EOF'
Ly8gRGlhZ27Ds3N0aWNvICsgYXJyZWdsbyBwdW50dWFsIHBhcmEgdW4gcGVkaWRvIGNvbmNyZXRv
IHF1ZSBubyBzZSBwdWVkZQovLyBjb25zdWx0YXIgZW4gL3NlZ3VpbWllbnRvIHBvcnF1ZSBzdSBw
dW50byBkZSBlbnRyZWdhIG5vIHRpZW5lIGPDs2RpZ28KLy8gcG9zdGFsIChvIFJhw7psIG5vIHNh
YmUgY3XDoWwgZXMpLgovLwovLyBNb3Rpdm8gZGUgZXN0ZSBzY3JpcHQ6IGVsIGJhY2tmaWxsIGRl
IGxvcyA0IGNsaWVudGVzIGRlIGRlbW8gZGVsIHNlZWQKLy8gKGBiYWNrZmlsbC1kZW1vLXBvc3Rh
bC1jb2Rlcy50c2ApIHNvbG8gY3VicmUgZXNvcyA0IC0tIHNpIHVuIHBlZGlkbyBkZQovLyBwcnVl
YmEgc2UgY3Jlw7MgY29udHJhIE9UUk8gY2xpZW50ZSBxdWUgdGFtYmnDqW4gdHV2aWVyYSBzdSBw
dW50byBkZQovLyBlbnRyZWdhIHNpbiBjw7NkaWdvIHBvc3RhbCAocG9yIGVqZW1wbG8sIHVuIGNs
aWVudGUgY3JlYWRvIGEgbWFubyBlbiBhbGfDum4KLy8gbW9tZW50byBhbnRlcmlvciBhIHF1ZSBz
ZSBleGlnaWVyYSBjw7NkaWdvIHBvc3RhbCBlbiB0b2RhcyBsYXMgdsOtYXMgZGUKLy8gYWx0YSks
IGVzZSBiYWNrZmlsbCBubyBsbyB0b2NhLiBFc3RlIHNjcmlwdCwgZW4gY2FtYmlvLCB2YSBkaXJl
Y3RvIGFsCi8vIHBlZGlkbyBwb3Igc3UgbsO6bWVybywgYXPDrSBubyBoYWNlIGZhbHRhIHNhYmVy
IGRlIGFudGVtYW5vIHF1w6kgY2xpZW50ZSBlcwovLyBuaSB0b2NhciBsYSBiYXNlIGRlIGRhdG9z
IGEgbWFuby4KLy8KLy8gVXNvIChkZXNkZSBiYWNrZW5kLyk6Ci8vICAgbnBtIHJ1biBkYjpmaXgt
b3JkZXItY3AgLS0gPG51bWVyby1kZS1wZWRpZG8+ICAgICAgICAgICAgICAgICAgLT4gc29sbyBk
aWFnbm9zdGljYSwgbm8gY2FtYmlhIG5hZGEKLy8gICBucG0gcnVuIGRiOmZpeC1vcmRlci1jcCAt
LSA8bnVtZXJvLWRlLXBlZGlkbz4gPGNvZGlnby1wb3N0YWw+ICAtPiBhZGVtw6FzLCByZWxsZW5h
IGVsIGPDs2RpZ28gcG9zdGFsIHNpIGVzdGFiYSB2YWPDrW8KLy8KLy8gRWplbXBsb3M6Ci8vICAg
bnBtIHJ1biBkYjpmaXgtb3JkZXItY3AgLS0gREVNTy0xNzg4NTI0MjkwMzgyCi8vICAgbnBtIHJ1
biBkYjpmaXgtb3JkZXItY3AgLS0gREVNTy0xNzg4NTI0MjkwMzgyIDI4OTA2Ci8vCi8vIE5vIHRv
Y2EgbmFkYSBzaSBlbCBwdW50byBkZSBlbnRyZWdhIFlBIHRpZW5lIGPDs2RpZ28gcG9zdGFsIC0t
IHBhcmEKLy8gY2FtYmlhciB1bm8geWEgZXhpc3RlbnRlLCBoYXpsbyBhIHByb3DDs3NpdG8gZWRp
dGFuZG8gZWwgcHVudG8gZGUgZW50cmVnYSwKLy8gbm8gY29uIGVzdGUgc2NyaXB0IChwZW5zYWRv
IHNvbG8gcGFyYSByZWxsZW5hciB1biBodWVjbywgbm8gcGFyYQovLyBzb2JyZXNjcmliaXIgdW4g
ZGF0byB5YSBjYXJnYWRvKS4KaW1wb3J0IHsgUHJpc21hQ2xpZW50IH0gZnJvbSAiQHByaXNtYS9j
bGllbnQiOwoKY29uc3QgcHJpc21hID0gbmV3IFByaXNtYUNsaWVudCgpOwoKYXN5bmMgZnVuY3Rp
b24gbWFpbigpIHsKICBjb25zdCBbb3JkZXJOdW1iZXJBcmcsIHBvc3RhbENvZGVBcmddID0gcHJv
Y2Vzcy5hcmd2LnNsaWNlKDIpOwoKICBpZiAoIW9yZGVyTnVtYmVyQXJnKSB7CiAgICBjb25zb2xl
LmVycm9yKAogICAgICAiRmFsdGEgZWwgbsO6bWVybyBkZSBwZWRpZG8uXG5cbiIgKwogICAgICAg
ICJVc286XG4iICsKICAgICAgICAiICBucG0gcnVuIGRiOmZpeC1vcmRlci1jcCAtLSA8bnVtZXJv
LWRlLXBlZGlkbz5cbiIgKwogICAgICAgICIgIG5wbSBydW4gZGI6Zml4LW9yZGVyLWNwIC0tIDxu
dW1lcm8tZGUtcGVkaWRvPiA8Y29kaWdvLXBvc3RhbD4iCiAgICApOwogICAgcHJvY2Vzcy5leGl0
Q29kZSA9IDE7CiAgICByZXR1cm47CiAgfQoKICBjb25zdCBvcmRlciA9IGF3YWl0IHByaXNtYS5v
cmRlci5maW5kRmlyc3QoewogICAgd2hlcmU6IHsgb3JkZXJOdW1iZXI6IHsgZXF1YWxzOiBvcmRl
ck51bWJlckFyZy50cmltKCksIG1vZGU6ICJpbnNlbnNpdGl2ZSIgfSB9LAogICAgaW5jbHVkZTog
ewogICAgICBjdXN0b21lcjogeyBzZWxlY3Q6IHsgYnVzaW5lc3NDb2RlOiB0cnVlLCBsZWdhbE5h
bWU6IHRydWUgfSB9LAogICAgICBkZWxpdmVyeVBvaW50OiB0cnVlLAogICAgfSwKICB9KTsKCiAg
aWYgKCFvcmRlcikgewogICAgY29uc29sZS5lcnJvcigKICAgICAgYE5vIGV4aXN0ZSBuaW5nw7pu
IHBlZGlkbyBjb24gZWwgbsO6bWVybyAiJHtvcmRlck51bWJlckFyZ30iIGVuIGVzdGEgYmFzZSBk
ZSBkYXRvcy5cbmAgKwogICAgICAgICJSZXZpc2EgcXVlIG5vIHRlbmdhIGVzcGFjaW9zIGRlIG3D
oXMsIHkgcXVlIGVzdMOpcyBhcHVudGFuZG8gYSBsYSBtaXNtYSBiYXNlIGRlICIgKwogICAgICAg
ICJkYXRvcyAoTmVvbikgZG9uZGUgc2UgY3Jlw7MgZWwgcGVkaWRvIC0tIENvZGVzcGFjZXMgeSBD
bG91ZCBSdW4gY29tcGFydGVuIGxhICIgKwogICAgICAgICJtaXNtYSBEQVRBQkFTRV9VUkwsIGFz
w60gcXVlIG5vIGRlYmVyw61hIHNlciB1biBwcm9ibGVtYSBkZSBlbnRvcm5vIGRpc3RpbnRvLCAi
ICsKICAgICAgICAicGVybyBjb252aWVuZSBkZXNjYXJ0YXJsbyBzaSBlbCBwZWRpZG8gc2UgY3Jl
w7MgaGFjZSB0aWVtcG8uIgogICAgKTsKICAgIHByb2Nlc3MuZXhpdENvZGUgPSAxOwogICAgcmV0
dXJuOwogIH0KCiAgY29uc3QgZHAgPSBvcmRlci5kZWxpdmVyeVBvaW50OwogIGNvbnNvbGUubG9n
KGBQZWRpZG8gZW5jb250cmFkbzogJHtvcmRlci5vcmRlck51bWJlcn0gKGlkICR7b3JkZXIuaWR9
KWApOwogIGNvbnNvbGUubG9nKGAgIENsaWVudGU6ICR7b3JkZXIuY3VzdG9tZXIuYnVzaW5lc3ND
b2RlfSDigJQgJHtvcmRlci5jdXN0b21lci5sZWdhbE5hbWV9YCk7CiAgY29uc29sZS5sb2coYCAg
UHVudG8gZGUgZW50cmVnYTogJHtkcC5pZH1gKTsKICBjb25zb2xlLmxvZyhgICBEaXJlY2Npw7Nu
OiAke2RwLmFkZHJlc3N9YCk7CiAgY29uc29sZS5sb2coYCAgUG9ibGFjacOzbjogJHtkcC5jaXR5
ID8/ICIoc2luIHBvYmxhY2nDs24pIn1gKTsKICBjb25zb2xlLmxvZyhgICBQcm92aW5jaWE6ICR7
ZHAucHJvdmluY2UgPz8gIihzaW4gcHJvdmluY2lhKSJ9YCk7CiAgY29uc29sZS5sb2coYCAgQ8Oz
ZGlnbyBwb3N0YWwgYWN0dWFsOiAke2RwLnBvc3RhbENvZGUgPz8gIihWQUPDjU8gLS0gcG9yIGVz
dG8gZmFsbGEgL3NlZ3VpbWllbnRvKSJ9YCk7CgogIGlmIChkcC5wb3N0YWxDb2RlKSB7CiAgICBj
b25zb2xlLmxvZygKICAgICAgIlxuRXN0ZSBwdW50byBkZSBlbnRyZWdhIFlBIHRpZW5lIGPDs2Rp
Z28gcG9zdGFsIC0tIHNpIGxhIGNvbnN1bHRhIGVuIC9zZWd1aW1pZW50byAiICsKICAgICAgICBg
c2lndWUgZmFsbGFuZG8sIHBydWViYSBleGFjdGFtZW50ZSBjb24gIiR7ZHAucG9zdGFsQ29kZX0i
ICh0YWwgY3VhbCwgc2luIGVzcGFjaW9zKS5gCiAgICApOwogICAgcmV0dXJuOwogIH0KCiAgaWYg
KCFwb3N0YWxDb2RlQXJnKSB7CiAgICBjb25zb2xlLmxvZygKICAgICAgIlxuTm8gc2UgaGEgaW5k
aWNhZG8gdW4gY8OzZGlnbyBwb3N0YWwgcGFyYSByZWxsZW5hci4gVnVlbHZlIGEgZWplY3V0YXIg
YXPDrSBwYXJhICIgKwogICAgICAgICJhcnJlZ2xhcmxvOlxuIiArCiAgICAgICAgYCAgbnBtIHJ1
biBkYjpmaXgtb3JkZXItY3AgLS0gIiR7b3JkZXIub3JkZXJOdW1iZXJ9IiA8Y29kaWdvLXBvc3Rh
bD5gCiAgICApOwogICAgcmV0dXJuOwogIH0KCiAgYXdhaXQgcHJpc21hLmRlbGl2ZXJ5UG9pbnQu
dXBkYXRlKHsKICAgIHdoZXJlOiB7IGlkOiBkcC5pZCB9LAogICAgZGF0YTogeyBwb3N0YWxDb2Rl
OiBwb3N0YWxDb2RlQXJnLnRyaW0oKSB9LAogIH0pOwoKICBjb25zb2xlLmxvZygKICAgIGBcbk9L
OiBjw7NkaWdvIHBvc3RhbCAiJHtwb3N0YWxDb2RlQXJnLnRyaW0oKX0iIGd1YXJkYWRvIGVuIGVs
IHB1bnRvIGRlIGVudHJlZ2EgZGUgZXN0ZSBwZWRpZG8uIGAgKwogICAgICBgWWEgcHVlZGVzIGNv
bnN1bHRhciAiJHtvcmRlci5vcmRlck51bWJlcn0iIGVuIC9zZWd1aW1pZW50byBjb24gZXNlIGPD
s2RpZ28gcG9zdGFsLmAKICApOwp9CgptYWluKCkKICAuY2F0Y2goKGVycikgPT4gewogICAgY29u
c29sZS5lcnJvcigiRXJyb3I6IiwgZXJyKTsKICAgIHByb2Nlc3MuZXhpdENvZGUgPSAxOwogIH0p
CiAgLmZpbmFsbHkoKCkgPT4gcHJpc21hLiRkaXNjb25uZWN0KCkpOwo=
B64EOF


echo "Compilando backend..."
(cd backend && npm run build)
echo "Listo. Ahora ejecuta, desde la raiz del repo:"
echo "  cd backend && npm run db:fix-order-cp -- DEMO-1788524290382"
echo "para ver que codigo postal tiene guardado ese pedido (o rellenarlo si esta vacio,"
echo "anadiendo el codigo postal como segundo argumento)."
